const postinfo = [
	{
		img: "assets/person/1.jpeg",
		name: "safak kocaoglu",
		posttime: "5 mins age",
		posttext: "Love for all, hatred for none",
		like: 22,
		postimg: "assets/post/1.jpeg",
	},
	{
		img: "assets/person/2.jpeg",
		name: "janell shrum",
		posttime: "5 mins age",
		posttext: "Love for all, hatred for none",
		like: 20,
		postimg: "assets/post/2.jpeg",
	},
	{
		img: "assets/person/3.jpeg",
		name: "alex durden",
		posttime: "5 mins age",
		posttext: "Love for all, hatred for none",
		like: 2,
		postimg: "assets/post/3.jpeg",
	},
	{
		img: "assets/person/4.jpeg",
		name: "dora hawks",
		posttime: "5 mins age",
		posttext: "Love for all, hatred for none",
		like: 7,
		postimg: "assets/post/4.jpeg",
	},
	{
		img: "assets/person/5.jpeg",
		name: "thomas holden",
		posttime: "5 mins age",
		posttext: "Love for all, hatred for none",
		like: 300,
		postimg: "assets/post/5.jpeg",
	},
	{
		img: "assets/person/6.jpeg",
		name: "shirley beauchamp",
		posttime: "5 mins age",
		posttext: "Love for all, hatred for none",
		like: 20,
		postimg: "assets/post/6.jpeg",
	},
	{
		img: "assets/person/7.jpeg",
		name: "travis thomas",
		posttime: "5 mins age",
		posttext: "Love for all, hatred for none",
		like: 1,
		postimg: "assets/post/7.jpeg",
	},
	{
		img: "assets/person/8.jpeg",
		name: "kristen thomas",
		posttime: "5 mins age",
		posttext: "Love for all, hatred for none",
		like: 8,
		postimg: "assets/post/8.jpeg",
	},
	{
		img: "assets/person/9.jpeg",
		name: "gary duty",
		posttime: "5 mins age",
		posttext: "Love for all, hatred for none",
		like: 18,
		postimg: "assets/post/9.jpeg",
	},
	{
		img: "assets/person/10.jpeg",
		name: "safak kocaoglu",
		posttime: "5 mins age",
		posttext: "Love for all, hatred for none",
		like: 10,
		postimg: "assets/post/10.jpeg",
	},
];

export default postinfo;